spring:
  datasource:
    username: virgil
    password: 1A2S3D4F
    url: jdbc:mysql://10.0.0.100:3306/myblog?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    generate-ddl: true
server:
  port: 8081

audience:
  iss: cyf
  secret: VGhpcyBpcyBhIHRlc3Qgb2YgbXkgYnJhbmQgbmV3IGxvZ2luIG1lY2hhbmlzbQ==
  expireSecond: 172800

logging:
  level:
    com: trace

imagePath: "C:/Users/ChenJ/Desktop/"
serverAddr: "http://localhost:8081"