spring:
  datasource:
    username: your_database_username
    password: your_database_password
    url: jdbc url
  jpa:
    generate-ddl: true
  redis:
    host: your redis host

  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

server:
  port: 8081

audience:
  iss: cyf
  secret: VGhpcyBpcyBhIHRlc3Qgb2YgbXkgYnJhbmQgbmV3IGxvZ2luIG1lY2hhbmlzbQ==
  expireSecond: 172800

imagePath: where should localImageService store image
serverAddr: "http://localhost:8081" The url of your server